# Generated by Django 6.0.2 on 2026-03-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('credit_rating', models.CharField(choices=[('AAA', 'Prime (AAA)'), ('AA', 'Hight Grade (AAA)'), ('A', 'Upper Medium (A)'), ('BBB', 'Lower Medium Grade (BBB)'), ('BB', 'Non-Investment Grade (BB)'), ('C', 'Highly Speculative (C)')], default='BBB', max_length=3)),
            ],
        ),
    ]
