# Generated by Django 6.0.2 on 2026-03-09 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=12, unique=True, verbose_name='ISIN')),
                ('bond_type', models.CharField(choices=[('GOV', 'Government'), ('CORP', 'Corporate'), ('MUNI', 'Municipal')], max_length=4)),
                ('face_value', models.DecimalField(decimal_places=2, help_text='Principal amount', max_digits=15)),
                ('coupon_rate', models.DecimalField(decimal_places=2, help_text='Percentage yield (e.g., 5.25)', max_digits=5)),
                ('issue_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='core.issuer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per bond at transaction', max_digits=15)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
