# Generated by Django 6.0.2 on 2026-03-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bond_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='industry',
            field=models.CharField(choices=[('Energy', 'Energy'), ('Materials', 'Materials'), ('Industrial', 'Industrials'), ('Financials', 'Financials'), ('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Utilities', 'Utilities'), ('Government', 'Government'), ('Real Estate', 'Real Estate'), ('Consumer Discretionary', 'Consumer Discretionary'), ('Consumer Staples', 'Consumer Staples'), ('Communication Services', 'Communication Services'), ('Other', 'Other')], default='Financials', max_length=100),
        ),
    ]
