# Generated by Django 6.0.2 on 2026-03-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_issuer_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='credit_rating',
            field=models.CharField(choices=[('AAA', 'Prime (AAA)'), ('AA', 'Hight Grade (AA)'), ('A', 'Upper Medium (A)'), ('BBB', 'Lower Medium Grade (BBB)'), ('BB', 'Non-Investment Grade (BB)'), ('C', 'Highly Speculative (C)')], default='BBB', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
