# Generated by Django 5.2 on 2026-04-24 00:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='coupon_rate',
            field=models.DecimalField(decimal_places=2, help_text='Percentage yield (e.g., 5.25)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='bond',
            name='face_value',
            field=models.DecimalField(decimal_places=2, help_text='Principal amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='bond',
            name='isin',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid ISIN format (e.g. US0378331005)', regex='^[A-Z]{2}[A-Z0-9]{9}[0-9]$')], verbose_name='ISIN'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per bond at transaction', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
